apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
type: Opaque
data:
  DATABASE_URL: postgres://postgres:senha123@auth-db:5432/auth_db?sslmode=disable
  PORT: "8001"
  MASTER_KEY: admin-secreto-123
