apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  namespace: evaluation-service
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: docker.io/redis:latest # Use a specific tag like redis:7 or redis:alpine for production
      ports:
        - containerPort: 6379 # Default Redis port
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
