apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: evaluation-service-scaler
  namespace: evaluation-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: evaluation-service # Nome do seu Deployment/StatefulSet
  minReplicaCount: 1
  maxReplicaCount: 3
  triggers:
  - type: oci-queue
    metadata:
      queueName: "TECHCHALLENGE-QUEUE"
      queueId: "ocid1.queue.oc1.sa-saopaulo-1.amaaaaaav7ovsvqak5i2ynzdafcqicepydvfd22ddyfttmqg6ztqnxrums6q" # ID da sua fila OCI
      pollingInterval: "30" # Segundos para verificar
      targetMessageCount: "10" # Alvo de mensagens por pod
