apiVersion: v1
kind: ConfigMap
metadata:
  name: flag-service-env
  namespace: flag-service
data:
  DATABASE_URL: postgres://postgres:togglemasterPass$123@togglemaster-rds-principal.clkeggq4owaz.us-east-1.rds.amazonaws.com:5432/flag_db?sslmode=require
  PORT: "8002"
  AUTH_SERVICE_URL: http://auth-service-svc.auth-service.svc.cluster.local:8001
