apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-service-env
  namespace: evaluation-service
data:
  PORT: "8004"

  # URL do seu Redis local
  REDIS_URL: rediss://togglemaster-redis-xm0rdk.serverless.use1.cache.amazonaws.com:6380

  # URLs dos outros serviços
  FLAG_SERVICE_URL: http://flag-service-svc.flag-service.svc.cluster.local:8002
  TARGETING_SERVICE_URL: http://targeting-service-svc.targeting-service.svc.cluster.local:8003

  #Chave de API
  SERVICE_API_KEY: tm_key_270a470dc74c00e18c0d4aaa4c25616046997c1ea7864d130fce1cda7f33588a 

  # --- Configuração da AWS (Obrigatório para o desafio) ---
  # Cole a URL da fila SQS que você criou no console da AWS
  AWS_SQS_URL: https://sqs.us-east-1.amazonaws.com/590183807419/togglemaster-queue 

  # Região da sua fila SQS
  AWS_REGION: us-east-1

  # Acesso AWS
  AWS_ACCESS_KEY_ID: ASIAYS2NSHG56YTYMVTI
  AWS_SECRET_ACCESS_KEY: ODargRdW171WsUtQ990RHc/eBRGe2OaoA8H53IFB
  AWS_SESSION_TOKEN: IQoJb3JpZ2luX2VjEKT//////////wEaCXVzLXdlc3QtMiJHMEUCIQCHi/SfagzUcHwopA0odaRghxNxb0mWHThuAOriPcQurwIgTa8qyTU4QTnjyVgyxcYP3yZhPEJwGADfAhOZjH0egO0qsgIIbRAAGgw1OTAxODM4MDc0MTkiDEpevw6mvIy1t9MPxCqPAuFgZpfrve22Y80v4QpLgz/CgWQXFBI7joXH3AtLEAVrQ4F7r5yznmtTCN1i13/BnLW4v0Dul3Q/pL6cBc9lZfTlcOqb9JBwIu5hbyW6Vbn10VsS0jCL7SsDrm5QIiAvsS+D8bF0J8hAgbnbmYsXAjl4s4+XtjG+dbu1rUVU1Skr3O7bfA9lmZXKdD7Kr80zWEzgCYS8mSj3CUVRDaIT+gMITOl0yEm2n7Yx6BYiLB2Ume37dUFZnp4iCj9mIhjfppuvX+yR5JiteMFHJrOkGSWzNz8hsgYDYOLXgjDwFNo0LO4SyHA0bIJGovIjieXNefWIydiEaAI0xGbpmBnxyeM1zeDZvwug95rIOI9U/MAwsMuvywY6nQHiLaL4pTJ42yUl511O4l6l3cjQZ/Te/+4vONIeAVfAUKcFhHNEAv7WuBNeItFkG/F3+615N8jYdEPcu9fqUXc4O4707H6oXFio50wlgbKuAoKPD/oyzxR7nGhZfCfEAwYzGtc67BuKnudefPyGPEwgjtRnUF2ro69j1qlavk5l2oCrRN+61yNXQXaBO7vfIV8RjDwLGY0aCqUUgM6h
